# Generated by Django 5.2.8 on 2025-11-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
